### ISSUE TITLE
Wrong display resolution and scale detection.[BUG] 

### ISSUE THREAD

**Issue by JohnClaw** [leafspark/AutoGGUF#6]
I launched compiled Windows executable of autogguf tool on my laptop, which screen resolution is 1920x1080p and got very small gui controls: 
![image](https://github.com/user-attachments/assets/07d0b668-23df-4788-8476-249d6dba9703)

It is very difficult to use your app while buttons and other controls are so tiny.

**Comment by leafspark** [comment]
Fixed in this commit: https://github.com/leafspark/AutoGGUF/commit/cb51a22d2f6c0524393105b7335f32a88180a34d

Here's the prebuilt binary: https://github.com/leafspark/AutoGGUF/releases/tag/v1.5.0

Changes:
- The entire window should be scrollable now.

**Comment by JohnClaw** [comment]
Thank you.
